name = "bens-bikes"
compatibility_date = "2025-09-28"
functions = "./functions"

[project]
compatibility_date = "2025-09-28"

[build]
command = "echo 'no build needed'"
cwd = "."
watch_dir = "."

[[r2_buckets]]
#binding = "r2_test
#bucket_name = "r2-test"
#preview_bucket_name = "r2-test

binding = "r2_images"
bucket_name = "r2-images"
preview_bucket_name = "r2-images"

#binding = "image_assets"
#bucket_name = "image-assets"
#preview_bucket_name = "image-assets"

[[d1_databases]]
binding = "DB"
database_name = "gallery-db"
database_id = "8a611c67-f995-4899-92af-134e12bf5461"

[[kv_namespaces]]
binding = "bens_bikes"
id = "ee0baf6c00ee41c8a377c74b6fbe1ad6"
preview_id = "ee0baf6c00ee41c8a377c74b6fbe1ad6" # same as ID if you're testing live
